### ISSUE TITLE
another nice example

### ISSUE THREAD

**Issue by illusionmanager** [giuven95/chatgpt-failures#1]
how many sons had Eise Eisinga in total

[i]Eise Eisinga was a Dutch amateur astronomer and clockmaker who built the Eisinga Planetarium in Franeker, Netherlands. Eisinga and his wife, Rinske Jans, had five sons in total[/i].

ChatGPT sounds very sure, but it is total nonsense. ChatGPT referred to the correct Eise Eisinga I was interested in, however he was never married to Rinske Jans. He married twice, with two boys (and a girl) from the first marriage (with Pietje Jacobs) and one son (and 2 girls) from the second marriage (with Trijntje Eelkes Sikkema)

**Comment by giuven95** [comment]
Thank you for opening this issue! I'll add it to the list

**Comment by giuven95** [comment]
Added it. Do you have a screenshot?

**Comment by illusionmanager** [comment]
[image: Untitled-2.png]

like this?

- frans

**Comment by giuven95** [comment]
Sorry, I don't see the picture

**Comment by illusionmanager** [comment]
[image: Untitled-2.png]
this time?

**Comment by illusionmanager** [comment]
perhaps edit a type i wrote once son, but of course that should have been
one son

-frans

**Comment by giuven95** [comment]
I think if you send the picture by mail it won't show up

**Comment by illusionmanager** [comment]
![Untitled-2](https://user-images.githubusercontent.com/79637793/213935215-2dcdf7a1-ad4f-4c9a-90e1-b72aff70816b.png)
You are right I was responding using email.

**Comment by giuven95** [comment]
Thank you! Added it
